project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
    - CNAME

website:
  title: "Jen Pokorny"
  google-analytics: "G-6Z3XGK2B15"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: github
        href: https://github.com/jpoko
      - icon: linkedin
        href: https://linkedin.com/in/jenpokorny
  page-footer:
    center: "&#169; 2026 Jen Pokorny &#8729; Made with [Quarto](https://quarto.org)"

format:
  html:
    theme: 
        - sandstone
        - custom.scss
    toc: false



